name: GitHub CI

on: [push]

defaults:
  run:
    shell: 'bash -o errexit -o nounset -o pipefail {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8-jdk-jammy, 8-jdk-focal, 11-jdk-jammy, 11-jdk-focal, 11-jdk-alpine, 17-jdk-jammy, 17-jdk-focal, 17-jdk-alpine, 18-jdk-jammy, 18-jdk-focal, 18-jdk-alpine]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env:
          version: ${{ matrix.version }}
        run: |
          directory=$(echo "jdk${version}" | sed 's/-jdk//' | sed 's/-jammy//')
          cd "${directory}"
          docker pull "eclipse-temurin:${version}"
          docker build --tag "gradle:${version}" .
      - name: test
        env:
          version: ${{ matrix.version }}
          expectedGradleVersion: 7.5.1
        run: |
          cd test
          ./run.sh "gradle:${version}" "${expectedGradleVersion}"
