name: GitHub CI

on: [push]

defaults:
  run:
    shell: 'bash -o errexit -o nounset -o pipefail {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvmType: [jdk, jre]
        version: [8, 11, 17]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env:
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
        run: |
          cd "${jvmType}${version}"
          docker pull "eclipse-temurin:${version}-jdk"
          docker build --tag "gradle:${jvmType}${version}" .
      - name: test
        env:
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
          expectedGradleVersion: 7.2
        run: |
          cd test
          ./run.sh "gradle:${jvmType}${version}" "${expectedGradleVersion}"
